name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '*/59 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_URL: https://wakapi.dev/api
          SHOW_SHORT_INFO: false
          SHOW_PROFILE_VIEWS: false
          SHOW_LOC_CHART: false
          SHOW_LANGUAGE_PER_REPO: false
          COMMIT_MESSAGE: 'docs: update ${{ matrix.readme }} with latest WakaTime stats'
